index:
    path: /
    defaults: { _controller: 'App\Controller\JobController::index' }
job_show:
    path: /job/{company}/{location}/{id}/{position}
    defaults: { _controller: 'App\Controller\JobController::show' }
    requirements:
        id: '\d+'
        company: '[A-Za-z0-9\-]+'
        location: '[A-Za-z0-9\-]+'
        position: '[A-Za-z0-9\-]+'
job_home:
   path: /accueil
   defaults: { _controller: 'App\Controller\JobController::home' }
job_profile:
   path: /profils
   defaults: { _controller: 'App\Controller\JobController::profile' }